Description: Ghostscript AWS Lambda Layer 
Parameters:
  AllowedPrincipal:
    Type: String
    Description: Account principal allowed to deploy this layer
    Default: '*'
Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs8.10
        - python3.6
        - ruby2.5
        - java8
        - go1.x
      Description: Ghostscript for AWS Lambda
      LayerName: ghostscript
      LicenseInfo: AGPL

  DeploymentPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: !Ref AllowedPrincipal

Outputs:
  LambdaLayer: 
    Value: !Ref LambdaLayer
